version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - phonenest_uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - MONGO=${MONGO_URI:-mongodb+srv://default:password@cluster0.example.mongodb.net/phonenest?retryWrites=true&w=majority}
      - JWT_SECRET=${JWT_SECRET:-yoursecretkey}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  phonenest_uploads: 