version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - MONGO=${MONGO_URI:-mongodb+srv://ibadkhan06:iffatbadar@cluster0.kk71xnf.mongodb.net/perecommerce?retryWrites=true&w=majority&appName=Cluster0}
      - JWT_SECRET=${JWT_SECRET:-ibad ninja secret}
    networks:
      - app-network
    volumes:
      - backend-uploads:/app/uploads
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  backend-uploads: 