export const BASE_URL= 'http://localhost:4000'
export const PRODUCT_URL= '/api/products'
export const UPLOAD_URL= '/api/uploads'
export const CATEGORY_URL= '/api/categories'
export const ORDER_URL= '/api/orders'