name: MERN App CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check repository structure
        run: |
          echo "Listing repository content:"
          ls -la
          echo "Checking for frontend directory:"
          ls -la frontend || echo "Frontend directory not found"
          echo "Checking for backend directory:"
          ls -la backend || echo "Backend directory not found"
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install frontend dependencies
        run: |
          if [ -d "frontend" ]; then
            cd frontend && npm ci
          else
            echo "Frontend directory not found, skipping"
          fi
        continue-on-error: true
        
      - name: Install backend dependencies
        run: |
          if [ -d "backend" ]; then
            cd backend && npm ci
          else
            echo "Backend directory not found, skipping"
          fi
        continue-on-error: true
        
      - name: Run ESLint on frontend
        run: |
          if [ -d "frontend" ]; then
            cd frontend && npx eslint src/ --ext .js,.jsx
          else
            echo "Frontend directory not found, skipping"
          fi
        continue-on-error: true
        
      - name: Run security audit on frontend
        run: |
          if [ -d "frontend" ]; then
            cd frontend && npm audit --audit-level=high --production
          else
            echo "Frontend directory not found, skipping"
          fi
        continue-on-error: true
        
      - name: Run security audit on backend
        run: |
          if [ -d "backend" ]; then
            cd backend && npm audit --audit-level=high --production
          else
            echo "Backend directory not found, skipping"
          fi
        continue-on-error: true

  build-and-test:
    runs-on: ubuntu-latest
    needs: code-quality
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check for docker-compose file
      run: |
        echo "Checking for docker-compose.yml:"
        ls -la docker-compose.yml || echo "docker-compose.yml not found"
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Install docker-compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    
    - name: Build docker-compose services
      run: |
        if [ -f "docker-compose.yml" ]; then
          docker-compose build
        else
          echo "docker-compose.yml not found, skipping build"
        fi
      continue-on-error: true
      
    - name: Run tests in backend container
      run: |
        if [ -f "docker-compose.yml" ] && [ -d "backend" ]; then
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose run --rm backend npm test
        else
          echo "Required files not found, skipping tests"
        fi
      continue-on-error: true
    
    - name: Run docker-compose services
      run: |
        if [ -f "docker-compose.yml" ]; then
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose up -d
        else
          echo "docker-compose.yml not found, skipping"
        fi
      continue-on-error: true
    
    - name: Wait for services to start
      run: |
        if [ -f "docker-compose.yml" ]; then
          sleep 30
        fi
      
    - name: Test if services are running
      run: |
        docker ps
        if [ -f "docker-compose.yml" ]; then
          curl -s --retry 5 --retry-delay 5 --retry-connrefused http://localhost || echo "Frontend not accessible"
          curl -s --retry 5 --retry-delay 5 --retry-connrefused http://localhost:4000/api/users || echo "Backend API not accessible"
        else
          echo "docker-compose.yml not found, skipping service checks"
        fi
      continue-on-error: true
    
    - name: Stop docker-compose services
      run: |
        if [ -f "docker-compose.yml" ]; then
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose down
        else
          echo "docker-compose.yml not found, skipping"
        fi
      continue-on-error: true

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Check directory structure for deployment
        run: |
          echo "Checking directory structure for deployment:"
          ls -la
          echo "Checking for frontend directory:"
          ls -la frontend || echo "Frontend directory not found"
          echo "Checking for backend directory:"
          ls -la backend || echo "Backend directory not found"
      
      # Build frontend for S3 deployment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install frontend dependencies
        run: |
          if [ -d "frontend" ]; then
            cd frontend && npm ci
          else
            echo "Frontend directory not found, skipping"
          fi
        continue-on-error: true
      
      - name: Build frontend production version
        run: |
          if [ -d "frontend" ]; then
            cd frontend && npm run build
          else
            echo "Frontend directory not found, skipping"
          fi
        continue-on-error: true
      
      # Docker Hub Login
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        continue-on-error: true
      
      # Build and push backend Docker image to Docker Hub
      - name: Build and push backend to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/phonenest-backend:latest"
        continue-on-error: true
      
      # Deploy frontend to S3
      - name: Configure AWS credentials for S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your preferred region
        continue-on-error: true
      
      - name: Deploy frontend to S3
        run: |
          if [ -d "frontend" ] && [ -d "frontend/dist" ]; then
            aws s3 sync frontend/dist s3://${{ secrets.S3_BUCKET_NAME }} --delete
          else
            echo "Frontend build directory not found, skipping S3 deployment"
          fi
        continue-on-error: true
      
      # Deploy backend to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update environment variables
            echo "MONGO=${{ secrets.MONGO_URI }}" > .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            
            # Pull the latest image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/phonenest-backend:latest
            
            # Stop any running container
            docker stop phonenest-backend || true
            docker rm phonenest-backend || true
            
            # Start the new container
            docker run -d \
              --name phonenest-backend \
              --restart always \
              -p 4000:4000 \
              --env-file .env \
              -v phonenest_uploads:/app/uploads \
              ${{ secrets.DOCKERHUB_USERNAME }}/phonenest-backend:latest
            
            # Clean up old images (optional)
            docker image prune -a -f
        continue-on-error: true 